#!/usr/bin/env bash
#
# ~/.bashrc
#
# shellcheck disable=SC1090

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Default alias
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Source global definitions
for f in "$HOME/.aliases" "$HOME/.env"; do
    [[ -f "$f" ]] && source "$f"
done

# Prompt
PS1='[\u@\h \W]\$ '
