# 

format = """[ ](bg:#585858)\
$os\
$username\
[](bg:#444444 fg:#585858)\
$hostname\
[](bg:#0087AF fg:#444444)\
$directory\
[](fg:#0087AF) \
$fill\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala
[ % ](bg:#303030)\
[](fg:#303030) 
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#585858"
style_root = "bg:#585858"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#585858"
disabled = true # Disabled by default

[fill]
symbol = " "

[hostname]
ssh_only = false
style = "bg:#444444"
format = '[$ssh_symbol]($style)[ $hostname ]($style)'

[directory]
style = "fg:#303030 bg:#0087AF"
read_only = ''
read_only_style="fg:#AF0000 bg:#0087AF"
format = '[ $path ]($style)[$read_only]($read_only_style)'
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#303030 bg:#AFD700"
format = '[](fg:#AFD700)[ $symbol $branch ]($style)'

[git_status]
style = "bg:#AFD700"
format = '[$all_status$ahead_behind ]($style)[](bg:#AFD700 fg:#303030 fg:#444444)'

[golang]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

