# Generated by dconf2nix: https://github.com/gvolpe/dconf2nix
#
# Usage:
#   1. Run: dconf dump / | dconf2nix > /path/to/this/file
#   2. Paste the output below (replace everything after this comment block)
#
# Note: This file is imported by default.nix with `lib.hm.gvariant` in scope
{ mkUint32, mkTuple }:

{
  # === GNOME Shell ===
  "org/gnome/shell" = {
    disable-user-extensions = false;
    disabled-extensions = [ ];
    enabled-extensions = [
      "arcmenu@arcmenu.com"
      "dash-to-panel@jderose9.github.com"
      "ding@rastersoft.com"
      "status-icons@gnome-shell-extensions.gcampax.github.com"
      "kimpanel@kde.org"
      "gsconnect@andyholmes.github.io"
      "appindicatorsupport@rgcjonas.gmail.com"
      "copyous@boerdereinar.dev"
    ];
    favorite-apps = [
      "brave-browser.desktop"
      "org.gnome.Nautilus.desktop"
      "code.desktop"
      "gitkraken.desktop"
      "virtualbox.desktop"
      "vesktop.desktop"
      "org.gnome.Console.desktop"
      "io.missioncenter.MissionCenter.desktop"
    ];
  };

  # === Desktop Background ===
  "org/gnome/desktop/background" = {
    color-shading-type = "solid";
    picture-options = "zoom";
    picture-uri = "file:///home/hayao/.wallpapers/venti.png";
    picture-uri-dark = "file:///home/hayao/.wallpapers/venti.png";
  };

  # === Desktop Screensaver ===
  "org/gnome/desktop/screensaver" = {
    lock-enabled = false;
    picture-uri = "file:///home/hayao/.wallpapers/venti.png";
  };

  # === Desktop Notifications ===
  "org/gnome/desktop/notifications" = {
    show-in-lock-screen = false;
  };

  # === Desktop Interface ===
  "org/gnome/desktop/interface" = {
    color-scheme = "prefer-dark";
    enable-hot-corners = false;
    icon-theme = "Papirus-Dark";
    show-battery-percentage = true;
    toolkit-accessibility = false;
  };

  # === Window Manager Preferences ===
  "org/gnome/desktop/wm/preferences" = {
    button-layout = "appmenu:minimize,maximize,close";
  };

  # === Mutter Settings ===
  "org/gnome/mutter" = {
    check-alive-timeout = mkUint32 60000;
    edge-tiling = true;
    overlay-key = "Super_L";
  };

  # === Input Sources ===
  "org/gnome/desktop/input-sources" = {
    sources = [ (mkTuple [ "xkb" "us" ]) ];
    xkb-options = [ "terminate:ctrl_alt_bksp" ];
  };

  # === Touchpad ===
  "org/gnome/desktop/peripherals/touchpad" = {
    two-finger-scrolling-enabled = true;
  };

  # === Session Settings ===
  "org/gnome/desktop/session" = {
    idle-delay = mkUint32 0;
  };

  # === Power Settings ===
  "org/gnome/settings-daemon/plugins/power" = {
    idle-dim = false;
    sleep-inactive-ac-type = "nothing";
    sleep-inactive-battery-type = "nothing";
  };

  # === Night Light ===
  "org/gnome/settings-daemon/plugins/color" = {
    night-light-schedule-automatic = false;
  };

  # === GNOME Console ===
  "org/gnome/Console" = {
    custom-font = "JetBrainsMonoNL Nerd Font Mono 10";
    ignore-scrollback-limit = true;
    use-system-font = false;
  };

  # === Nautilus Preferences ===
  "org/gnome/nautilus/preferences" = {
    default-folder-viewer = "icon-view";
    show-image-thumbnails = "always";
  };

  "org/gnome/nautilus/compression" = {
    default-compression-format = "zip";
  };

  # === GNOME Text Editor ===
  "org/gnome/TextEditor" = {
    restore-session = false;
  };

  # === GNOME Terminal ===
  "org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9" = {
    audible-bell = false;
    scrollback-unlimited = true;
  };

  # === Shell Keybindings ===
  "org/gnome/shell/keybindings" = {
    toggle-message-tray = [ ];
  };

  # === dconf-editor ===
  "ca/desrt/dconf-editor" = {
    show-warning = false;
  };

  # === GTK File Chooser Settings ===
  "org/gtk/gtk4/settings/file-chooser" = {
    show-hidden = true;
    sort-directories-first = false;
    view-type = "list";
  };

  "org/gtk/settings/file-chooser" = {
    show-hidden = true;
    show-size-column = true;
    show-type-column = true;
    sort-directories-first = false;
  };

  # === Extension: ArcMenu ===
  "org/gnome/shell/extensions/arcmenu" = {
    enable-horizontal-flip = false;
    menu-height = 700;
    menu-layout = "Whisker";
    multi-monitor = true;
    # Note: pinned-apps uses complex GVariant format - configure manually via dconf-editor
    search-entry-border-radius = mkTuple [ true 25 ];
    searchbar-default-top-location = "Bottom";
  };

  # === Extension: Dash to Panel ===
  "org/gnome/shell/extensions/dash-to-panel" = {
    animate-appicon-hover-animation-extent = ''{"RIPPLE":4,"PLANK":4,"SIMPLE":1}'';
    dot-position = "BOTTOM";
    hotkeys-overlay-combo = "TEMPORARILY";
    window-preview-title-position = "TOP";
  };

  # === Extension: Desktop Icons NG (DING) ===
  "org/gnome/shell/extensions/ding" = {
    add-volumes-opposite = false;
    check-x11wayland = true;
    icon-size = "small";
    show-home = false;
    show-volumes = false;
  };

  # === Extension: GSConnect ===
  "org/gnome/shell/extensions/gsconnect" = {
    devices = [ ];
    missing-openssl = false;
    name = "XPS9350";
  };

  # === Extension: Copyous (Pano successor) ===
  # Note: Pano is archived and doesn't support GNOME 49, using Copyous instead
  "org/gnome/shell/extensions/copyous" = {
    clipboard-position-vertical = "bottom";
    disable-hljs-dialog = false;
    open-clipboard-dialog-shortcut = [ "<Super>v" ];
  };
}
