name: Test Home Manager

on: [push, pull_request]

jobs:
  build-x86_64:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build the flake
        run: nix build .#homeConfigurations.hayao@unstable.activationPackage --show-trace

      - name: Test installation
        # run: nix profile install --profile /tmp/test-profile .
        run: nix run github:nix-community/home-managner -- switch --flake .#hayao@unstable

  build-arm64:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build the flake
        run: nix build .#homeConfigurations.hayao@darwin-unstable.activationPackage --show-trace

      - name: Test installation
        # run: nix profile install --profile /tmp/test-profile .
        run: nix run github:nix-community/home-managner -- switch --flake .#darwin-unstable
